# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cracker
  pod 'SwiftLint'
  pod 'SideMenu', '~> 6.0'
  pod 'Hero'
  pod 'RAMAnimatedTabBarController'
  pod 'IQKeyboardManagerSwift'
  pod 'lottie-ios'
  pod 'PKHUD', '~> 5.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Firebase/Crashlytics'

end
